.TH IOTOP "8" "September 30, 2020"
.SH NAME
iotop \- simple top\-like I/O monitor
.SH SYNOPSIS
.B iotop
[\fIOPTIONS\fR]
.SH DESCRIPTION
iotop watches I/O usage information output by the Linux kernel (requires
2.6.20 or later) and displays a table of current I/O usage by processes
or threads on the system. At least the CONFIG_TASK_DELAY_ACCT,
CONFIG_TASK_IO_ACCOUNTING, CONFIG_TASKSTATS and CONFIG_VM_EVENT_COUNTERS
options need to be enabled in your Linux kernel build configuration.
.PP
iotop displays columns for the I/O bandwidth read and written by each
process/thread during the sampling period. It also displays the percentage
of time the thread/process spent while swapping in and while waiting on I/O. For each process, its I/O priority (class/level) is shown.
.PP
In addition, the total I/O bandwidth read and written during the sampling
period is displayed at the top of the interface.
\fBTotal DISK READ\fR and \fBTotal DISK WRITE\fR values represent total read
and write bandwidth between processes and kernel threads on the one side and
kernel block device subsystem on the other. While \fBCurrent DISK READ\fR and
\fBCurrent DISK WRITE\fR values represent corresponding bandwidths for current
disk I/O between kernel block device subsystem and underlying hardware (HDD, SSD, etc.).
Thus \fBTotal\fR and \fBCurrent\fR values may not be equal at any given moment of time
due to data caching and I/O operations reordering that take place inside Linux kernel.
.PP
Use the left and right arrows to change the sorting, r to reverse the
sorting order, o to toggle the \-\-only option, p to toggle the \-\-processes option, a to toggle the \-\-accumulated option, q to quit or i to change the priority of a thread or a process's thread(s). Any other key will force a refresh.
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR
Show the version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
Show usage information and exit
.TP
\fB\-o\fR, \fB\-\-only\fR
Only show processes or threads actually doing I/O, instead of showing all processes or threads. This can be dynamically toggled by pressing o.
.TP
\fB\-b\fR, \fB\-\-batch\fR
Turn on non\-interactive mode.
Useful for logging I/O usage over time.
.TP
\fB\-n\fR NUM, \fB\-\-iter\fR=\fINUM\fR
Set the number of iterations before quitting (never quit by default).
This is most useful in non\-interactive mode.
.TP
\fB\-d\fR SEC, \fB\-\-delay\fR=\fISEC\fR
Set the delay between iterations in seconds (1 second by default).
Accepts non-integer values such as 1.1 seconds.
.TP
\fB\-p\fR PID, \fB\-\-pid\fR=\fIPID\fR
A list of processes/threads to monitor (all by default).
.TP
\fB\-u\fR USER, \fB\-\-user\fR=\fIUSER\fR
A list of users to monitor (all by default)
.TP
\fB\-P\fR, \fB\-\-processes\fR
Only show processes. Normally iotop shows all threads.
.TP
\fB\-a\fR, \fB\-\-accumulated\fR
Show accumulated I/O instead of bandwidth. In this mode, iotop shows the amount of I/O processes have done since iotop started.
.TP
\fB\-k\fR, \fB\-\-kilobytes\fR
Use kilobytes instead of a human friendly unit. This mode is useful when scripting the batch mode of iotop. Instead of choosing the most appropriate unit iotop will display all sizes in kilobytes.
.TP
\fB\-t\fR, \fB\-\-time\fR
Add a timestamp on each line (implies \-\-batch). Each line will be prefixed by the current time.
.TP
\fB\-c\fR, \fB\-\-fullcmdline\fR
Show processes' full file path & parameters.
.TP
\fB\-1\fR, \fB\-\-hide-pid\fR
Hide PID/TID column
.TP
\fB\-2\fR, \fB\-\-hide-prio\fR
Hide PRIO column
.TP
\fB\-3\fR, \fB\-\-hide-user\fR
Hide USER column
.TP
\fB\-4\fR, \fB\-\-hide-read\fR
Hide DISK READ column
.TP
\fB\-5\fR, \fB\-\-hide-write\fR
Hide DISK WRITE column
.TP
\fB\-6\fR, \fB\-\-hide-swapin\fR
Hide SWAPIN column
.TP
\fB\-7\fR, \fB\-\-hide-io\fR
Hide IO column
.TP
\fB\-8\fR, \fB\-\-hide-graph\fR
Hide GRAPH column
.TP
\fB\-9\fR, \fB\-\-hide-command\fR
Hide COMMAND column
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress some lines of header (implies \-\-batch). This option can be specified up to three times to remove header lines.
.RS
.PD 0
.TP
.B \-q
column names are only printed on the first iteration,
.TP
.B \-qq
column names are never printed,
.TP
.B \-qqq
the I/O summary is never printed.
.RE
.PD 1
.TP
\fB\-H\fR, \fB\-\-no\-help\fR
Suppress the keyboard shortcuts help display.
.PD 1
.SH KEYBOARD SHORTCUTS
.TP
\fBq\fR, \fBQ\fR
Exit
.TP
\fB<space>\fR, \fBr\fR, \fBR\fR
Toggle sort order
.TP
\fB<home>\fR
Sort by column PID/TID
.TP
\fB<end>\fR
Sort by column COMMAND
.TP
\fB<right>\fR
Sort by next column
.TP
\fB<left>\fR
Sort by previous column
.TP
\fBo\fR, \fBO\fR
Toggle showing only processes with IO activity
.TP
\fBp\fR, \fBP\fR
Toggle showing processes/threads
.TP
\fBa\fR, \fBA\fR
Toggle showing accumulated/current values
.TP
\fB?\fR, \fBh\fR, \fBH\fR
Toggle showing shortcut help
.TP
\fBc\fR, \fBC\fR
Toggle showing full command line
.TP
\fB1\fR, \fB2\fR, \fB3\fR, \fB4\fR, \fB5\fR, \fB6\fR, \fB7\fR, \fB8\fR, \fB9\fR
Toggle showing the column (column number corresponds to the shortcut)
.TP
\fBi\fR, \fBI\fR
IOnice a process/thread (depends on process/thread display mode)
.TP
\fBu\fR, \fBU\fR
Toggle using Unicode/ASCII characters for pseudo graph
.SH SEE ALSO
.BR ionice (1),
.BR top (1),
.BR vmstat (1),
.BR atop (1),
.BR htop (1)
.SH AUTHOR
The original Python iotop implementation was written by Guillaume Chazarain. This rewrite in C started in 2014 by Vyacheslav Trushkin and
reworked to include all features from the original Python version in 2020 by Boian Bonev.
.PP
This manual page was started by Paul Wise for the
Debian project and is placed in the public domain.
